language: python
python:
  - "3.5"

cache:
  - pip

install:
  - pip3 install -r requirements.txt

jobs:
  include:
    - stage: compile
      script: python3.5 -m compileall lib/
    - stage: test
      script: bash etc/pytest.sh
    - script: sleep 10   # for unit tests in future
    - stage: deploy
      skip_cleanup: true
      provider: script
      script: bash etc/deploy_docs.sh
      on:
        branch: development 

notifications:
  email:
    recipients:
      - achyudhk@gmail.com
      - tsrkp@goa.bits-pilani.ac.in
      - f20150530@goa.bits-pilani.ac.in
      - f20160057@goa.bits-pilani.ac.in
      - f20160718@goa.bits-pilani.ac.in
    on_success: change
    on_failure: always
