language: python
python:
  - "3.5"

install:
  - pip3 install -r requirements.txt

script:
  - py.test -v --color=yes

deploy:
  skip_cleanup: true
  provider: script
  script: bash etc/deploy_docs.sh
  on:
    branch: development

notifications:
  email:
    recipients:
      - achyudhk@gmail.com
      - tsrkp@goa.bits-pilani.ac.in
      - f20150530@goa.bits-pilani.ac.in
      -f20160057@goa.bits-pilani.ac.in
      -f20160718@goa.bits-pilani.ac.in
    on_success: change
    on_failure: always

branches:
  only:
  - master
  - development
